//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaServeur.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Transactions = new HashSet<Transaction>();
            this.TransactionPeriodiques = new HashSet<TransactionPeriodique>();
        }
    
        public int id { get; set; }
        public int idPorteFeuille { get; set; }
        public string designation { get; set; }
        public string descript { get; set; }

        [JsonIgnore]
        public virtual PorteFeuille PorteFeuille { get; set; }
        [JsonIgnore]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [JsonIgnore]
        public virtual ICollection<TransactionPeriodique> TransactionPeriodiques { get; set; }
    }
}
