//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaServeur.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.PrivilegeUtilisateurs = new HashSet<PrivilegeUtilisateur>();
        }
    
        public int id { get; set; }
        public string designation { get; set; }
        [JsonIgnore]
        public virtual ICollection<PrivilegeUtilisateur> PrivilegeUtilisateurs { get; set; }
    }
}
