//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaServeur.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegeUtilisateur
    {
        public int idUtilisateur { get; set; }
        public int idPrivilege { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        [JsonIgnore]
        public virtual Privilege Privilege { get; set; }
        [JsonIgnore]
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
