//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaServeur.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Transfert
    {
        public int id { get; set; }
        public int idCompteExpediteur { get; set; }
        public int idCompteRecepteur { get; set; }
        public double montant { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string designation { get; set; }
        [JsonIgnore]
        public virtual Compte Compte { get; set; }
        [JsonIgnore]
        public virtual Compte Compte1 { get; set; }
    }
}
