//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaServeur.Models
{
    using System;
    using Newtonsoft.Json; 
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Comptes = new HashSet<Compte>();
            this.PrivilegeUtilisateurs = new HashSet<PrivilegeUtilisateur>();
        }
    
        public int id { get; set; }
        public int idPorteFeuille { get; set; }
        public string nomDeCompte { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string roleUtilisateur { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Compte> Comptes { get; set; }
       
        [JsonIgnore]
        public virtual PorteFeuille PorteFeuille { get; set; }
        
        [JsonIgnore]
        public virtual ICollection<PrivilegeUtilisateur> PrivilegeUtilisateurs { get; set; }
    }
}
